projetodiam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemestrado/', include('sitemestrado.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

sitemestrado/urls.py
from django.urls import include, path
from . import views

app_name = 'sitemestrado'

urlpatterns = [
    path("", views.index, name='index'),
    path('loginpage', views.loginpage, name="loginpage"),
    path('logoutpage', views.logoutpage, name="logoutpage"),
    path('registar', views.registar, name='registar'),
    path('eventos', views.eventos, name='eventos'),
    path('disciplinas', views.disciplinas, name="disciplinas"),
    path('forum', views.forum, name="forum"),
    path('infopessoal', views.infopessoal, name="infopessoal"),
    path('criarnoticia', views.criarnoticia, name="criarnoticia"),
    path('noticia_<int:noticia_id>', views.detalhenoticia, name="detalhenoticia"), 
    path('adicionarevento', views.adicionarevento, name="adicionarevento"),
    path('evento_<int:evento_id>', views.detalheevento, name="detalheevento"),
    path('utilizador_<int:outrapessoa_id>', views.infooutrapessoa, name="infooutrapessoa"),
    path('editarinfopessoal', views.editarinfopessoal, name="editarinfopessoal"),
    path('criarpost', views.criarpost, name="criarpost"),
    path('searchuser',views.searchuser, name="searchuser"),
    path('searcheventos',views.searcheventos, name="searcheventos"),
    path('post_<int:post_id>', views.detalhepost, name="detalhepost"),
    path('disciplina_<int:disc_id>',views.detalhedisc, name="detalhedisc"),
    path('searchdisciplina',views.searchdisciplina,name ="searchdisciplina"),
    path('searchpost',views.searchpost,name="searchpost"),
    path('criardisciplina',views.criardisciplina,name="criardisciplina")
]

sitemestrado/models.py
from datetime import datetime, date
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Aluno(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    imagem = models.TextField()
    is_privado = models.BooleanField(default=False)
    area_trab = models.TextField()
    linkedin = models.TextField()
    is_professor = models.BooleanField(default=False)

    def add_foto(self,foto):
       self.imagem=foto
       self.save()

    def set_professor(self):
       self.is_professor = True
       self.is_privado = False
       self.save()  

    def set_aluno(self):
       self.is_professor = False
       self.save()  

    def __str__(self):
        return self.user.username

  

class Evento(models.Model):
    evento_nome = models.CharField(max_length=200)
    evento_conteudo = models.TextField()
    evento_data = models.DateTimeField() 
    evento_local = models.CharField(max_length=200)
    evento_capa = models.TextField()
    evento_autor = models.CharField(max_length=200)
    evento_autor_id = models.IntegerField()
    evento_nr_inscritos = models.IntegerField(default=0)

    participantes_alunos = models.ManyToManyField('Aluno',related_name='eventos', default = None)

    def __str__(self):
      return self.evento_nome
    
    def add_capa(self,capa):
       self.evento_capa=capa
       self.save()
    
    def adicionar_imagem(self,imagem):
       nova_imagem = Imagem(evento=self,imagem=imagem)
       nova_imagem.save()

    def adicionar_ficheiro(self,ficheiro,nome):
       novo_ficheiro = Ficheiro(evento=self,ficheiro=ficheiro,ficheiro_nome=nome)
       novo_ficheiro.save()

    @property
    def is_past_due(self):
       return timezone.now() > self.evento_data
   
    def add_inscrito(self,user):
       self.participantes_alunos.add(user.aluno)
       self.evento_nr_inscritos += 1
       self.save()

    def remove_inscrito(self,user):
       self.participantes_alunos.remove(user.aluno)
       self.evento_nr_inscritos -= 1
       self.save()
    
    def get_next_three(lista):
       filtered = filter(lambda evento: evento.evento_data >= timezone.now(), lista)
       return list(filtered)[-3:]

    def isInscrito(self,user):
      return self.participantes_alunos.contains(user.aluno) 
         

   
class Noticia(models.Model):
    noticia_nome = models.CharField(max_length=200)
    noticia_conteudo = models.TextField()
    noticia_data_pub = models.DateTimeField(default=datetime.now())
    noticia_autor = models.CharField(max_length=200)
    noticia_autor_id = models.IntegerField()
    noticia_privacidade = models.BooleanField(default=False)
    noticia_capa = models.TextField()

    def __str__(self):
      return self.noticia_nome
    
    def add_capa(self,capa):
       self.noticia_capa=capa
       self.save()
    
    def adicionar_imagem(self,imagem):
       nova_imagem = Imagem(noticia=self,imagem=imagem)
       nova_imagem.save()

    def adicionar_ficheiro(self,ficheiro,nome):
       novo_ficheiro = Ficheiro(noticia=self,ficheiro=ficheiro,ficheiro_nome=nome)
       novo_ficheiro.save()

class Disciplina(models.Model):
    disciplina_nome = models.CharField(max_length=200)
    disciplina_sigla = models.CharField(max_length=200)
    professores = models.ManyToManyField('Aluno',related_name='disciplinas', default = None)

    def __str__(self):
      return self.disciplina_nome

class Post(models.Model):
    post_nome = models.CharField(max_length=200)
    post_conteudo = models.TextField()
    post_capa = models.TextField()
    post_autor = models.CharField(max_length=200)
    post_autor_id = models.IntegerField()
    post_data_pub = models.DateTimeField(default=datetime.now())
    referencia_youtube = models.TextField()
    post_nr_respostas = models.IntegerField(default=0)
    #  ChoiceField= forms.ModelChoiceField(
     #    queryset = Disciplina.objects.all(),
      #   widget=forms.Select
      #)
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE, default = None, null=True)

    def add_capa(self,capa):
       self.post_capa=capa
       self.save()

    def add_resposta(self):
       self.post_nr_respostas += 1
       self.save()

    def adicionar_imagem(self,imagem):
       nova_imagem = Imagem(post=self,imagem=imagem)
       nova_imagem.save()

    def adicionar_ficheiro(self,ficheiro,nome):
       novo_ficheiro = Ficheiro(post=self,ficheiro=ficheiro,ficheiro_nome=nome)
       novo_ficheiro.save()

    def __str__(self):
      return self.post_nome
    

class Resposta(models.Model):
   post = models.ForeignKey(Post,on_delete=models.CASCADE)
   resposta_autor = models.CharField(max_length=200)
   resposta_autor_id = models.IntegerField()
   resposta_conteudo = models.TextField()
   resposta_data_pub = models.DateTimeField(default=datetime.now())

   def __str__(self):
      return self.resposta_conteudo
   

class Ficheiro(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, related_name='ficheiros',default=None,null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='ficheiros',default=None,null=True)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, related_name='ficheiros',default=None,null=True)
    ficheiro = models.TextField()
    ficheiro_nome = models.CharField(max_length=200)

class Imagem(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, related_name='imagens',default=None,null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='imagens',default=None,null=True)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, related_name='imagens',default=None,null=True)
    imagem = models.TextField()

sitemestrado/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Aluno, Disciplina, Noticia, Evento, Post, Resposta
from datetime import datetime
from django.core.files.storage import FileSystemStorage

# Create your views here.

def index(request):
    noticias_list = Noticia.objects.order_by('-noticia_data_pub')
    eventos_list = Evento.objects.order_by('-evento_data')
    three_eventos = Evento.get_next_three(eventos_list)
    users_list = User.objects.all()
    context = {
        'noticias_list' : noticias_list,
        'three_eventos' : three_eventos,
        'users_list' : users_list 
    }
    return render(request, 'sitemestrado/index.html',context)

def infopessoal(request):
    noticias_list = Noticia.objects.order_by('-noticia_data_pub')
    if request.user.aluno:
        eventos_list = request.user.aluno.eventos.all()
    context = {
         'noticias_list' : noticias_list,
         'eventos_list' : eventos_list
    }
    return render(request, 'sitemestrado/infopessoal.html', context)


def editarinfopessoal(request):
    if request.method == "POST" :
        user = User.objects.get(id=request.user.id)
        if request.POST.get("primnome"):
            user.first_name= request.POST.get("primnome")
        if request.POST.get("ultnome"):
            user.last_name=request.POST.get("ultnome")
        if request.POST.get("email"):
            user.email= request.POST.get("email")
        if user.aluno:
            aluno = Aluno.objects.get(user_id=request.user.id)
            if request.POST.get("area_trab"):
                aluno.area_trab= request.POST.get("area_trab")
            if request.POST.get("linkedin"):
                aluno.linkedin = request.POST.get("linkedin")
            privado = request.POST.get('privado')
            if privado == 'on':
                aluno.is_privado = True
            else:
                aluno.is_privado = False
            if 'imagem' in request.FILES:
                imagem = request.FILES.get('imagem')
                fs = FileSystemStorage()
                imagename = fs.save(imagem.name,imagem)
                aluno.add_foto("/sitemestrado/static/media/" + imagename)
            aluno.save()
        user.save()
        return HttpResponseRedirect(reverse('sitemestrado:infopessoal'))
    return render(request, 'sitemestrado/editarinfopessoal.html')

def loginpage(request):
    if request.method == 'POST':
        u = request.POST.get('username')
        p = request.POST.get('password')
        user = authenticate(username=u, password=p)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('sitemestrado:index'))
        else:
            '''para depois'''
    return render(request, 'sitemestrado/loginpage.html')

def logoutpage(request):
    logout(request)
    return HttpResponseRedirect(reverse('sitemestrado:index'))

def registar(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        nome = request.POST.get('nome')
        apelido = request.POST.get('apelido')
        email = request.POST.get('email')
        password = request.POST.get('password')
        privado = request.POST.get('perfilprivado')
        if privado == 'on':
            privado = True
        else:
            privado = False
        u = User.objects.create_user(username, email, password, first_name = nome, last_name= apelido)
        u.save()
        aluno = Aluno(user=u, is_privado=privado)
        aluno.save()
        return HttpResponseRedirect(reverse('sitemestrado:loginpage'))
    return render(request, 'sitemestrado/registar.html')

def eventos(request):
    eventos_list = Evento.objects.order_by('-evento_data')
    context = {
        'eventos_list' : eventos_list 
    }
    return render(request, 'sitemestrado/eventos.html',context)

@login_required(login_url='/sitemestrado/loginpage')
def forum(request):
    post_list = Post.objects.order_by('-post_data_pub')
    context = {
        'post_list' : post_list
    }
    return render(request, 'sitemestrado/forum.html',context)

@login_required(login_url='/sitemestrado/loginpage')
def criarnoticia(request):
    if request.method == 'POST':
        nome = request.POST.get('titulo')
        conteudo = request.POST.get('conteudo')
        priv = request.POST.get('privada')
        if priv == 'on':
            priv = True
        else:
            priv = False
        q = Noticia(noticia_nome=nome, 
                    noticia_conteudo=conteudo, 
                    noticia_autor=request.user.first_name + " " + request.user.last_name, 
                    noticia_autor_id=request.user.id,
                    noticia_privacidade=priv,
                    )
        if 'imagem' in request.FILES:
            imagem = request.FILES.get('imagem')
            fs = FileSystemStorage()
            imagename = fs.save(imagem.name,imagem)
            q.add_capa("/sitemestrado/static/media/" + imagename)
        q.save()
        if 'imagens' in request.FILES:
            imagens = request.FILES.getlist('imagens')
            fs = FileSystemStorage()
            for f in imagens:
                imagename = fs.save(f.name,f)
                q.adicionar_imagem("/sitemestrado/static/media/" + imagename)
        if 'ficheiros' in request.FILES:
            ficheiros = request.FILES.getlist('ficheiros')
            fs = FileSystemStorage()
            for f in ficheiros:
                ficheironame = fs.save(f.name,f)
                q.adicionar_ficheiro("/sitemestrado/static/media/" + ficheironame,ficheironame)
        return HttpResponseRedirect(reverse('sitemestrado:index'))
    return render(request, 'sitemestrado/criarnoticia.html')

def detalhenoticia(request, noticia_id):
    noticia = get_object_or_404(Noticia, pk=noticia_id)
    return render(request, 'sitemestrado/detalhenoticia.html',{'noticia' : noticia})

@login_required(login_url='/sitemestrado/loginpage')
def adicionarevento(request):
    if request.method == 'POST':
        nome = request.POST.get('titulo')
        conteudo = request.POST.get('conteudo')
        data = request.POST.get('data')
        local = request.POST.get('local')
        q = Evento(evento_nome=nome, 
                    evento_conteudo=conteudo, 
                    evento_data=data,
                    evento_local=local,
                    evento_autor=request.user.first_name + " " + request.user.last_name, 
                    evento_autor_id=request.user.id,
                    )
        if 'imagem' in request.FILES:
            imagem = request.FILES.get('imagem')
            fs = FileSystemStorage()
            imagename = fs.save(imagem.name,imagem)
            q.add_capa("/sitemestrado/static/media/" + imagename)
        q.save()
        if 'imagens' in request.FILES:
            imagens = request.FILES.getlist('imagens')
            fs = FileSystemStorage()
            for f in imagens:
                imagename = fs.save(f.name,f)
                q.adicionar_imagem("/sitemestrado/static/media/" + imagename)
        if 'ficheiros' in request.FILES:
            ficheiros = request.FILES.getlist('ficheiros')
            fs = FileSystemStorage()
            for f in ficheiros:
                ficheironame = fs.save(f.name,f)
                q.adicionar_ficheiro("/sitemestrado/static/media/" + ficheironame,ficheironame)
        return HttpResponseRedirect(reverse('sitemestrado:index'))
    return render(request, 'sitemestrado/adicionarevento.html')

def detalheevento(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    inscrito = False
    if request.user.is_authenticated:
        if not request.user.is_staff: 
            if request.user.aluno:
                inscrito = Evento.isInscrito(evento,request.user)
    if request.method == 'POST':
        if request.user.aluno:
            if evento.participantes_alunos.contains(request.user.aluno):
                evento.remove_inscrito(request.user)
            else:
                evento.add_inscrito(request.user)
        return HttpResponseRedirect(reverse('sitemestrado:detalheevento',args=[evento_id]))
    return render(request, 'sitemestrado/detalheevento.html',{'evento' : evento, 'inscrito': inscrito})

def criarpost(request):
    if request.method == 'POST':
        nome = request.POST.get('titulo')
        conteudo = request.POST.get('conteudo')
        referenciayoutube = request.POST.get('referenciayoutube')
        disc = request.POST.get('disciplina')
        if(disc):
            d = Disciplina.objects.get(pk=disc)
        else:
            d= None
        q = Post(post_nome=nome, 
                    post_conteudo=conteudo, 
                    referencia_youtube = referenciayoutube,
                    post_autor=request.user.first_name + " " + request.user.last_name, 
                    post_autor_id=request.user.id,
                    disciplina=d
                    )
        if 'imagem' in request.FILES:
            imagem = request.FILES.get('imagem')
            fs = FileSystemStorage()
            imagename = fs.save(imagem.name,imagem)
            q.add_capa("/sitemestrado/static/media/" + imagename)
        q.save()
        if 'imagens' in request.FILES:
            imagens = request.FILES.getlist('imagens')
            fs = FileSystemStorage()
            for f in imagens:
                imagename = fs.save(f.name,f)
                q.adicionar_imagem("/sitemestrado/static/media/" + imagename)
        if 'ficheiros' in request.FILES:
            ficheiros = request.FILES.getlist('ficheiros')
            fs = FileSystemStorage()

sitemestrado/templates/sitemestrado/disciplinas.html
{% extends "sitemestrado/index.html" %}
{% block title %}
<title> Disciplinas </title>
{% endblock %}
{%block searchbar%}
<form class='search-form' method=POST action ="{% url 'sitemestrado:searchdisciplina' %}">
  {% csrf_token %}
 <input type='search' placeholder='Search' name ="searched">
 <button class'search-btn' type='submit'>Search</button>
</form>  
{%endblock%}

{% block eventos-list %}
{% endblock %}

{% block content %}
<div class="noticias-title-and-button">
    <h2 style="display: inline-block;padding-left:0.5%;"> Discplinas </h2> {% if request.user.is_staff %} <button class="buttons-default" onclick="window.open('criardisciplina','_self')"> Criar nova disciplina </button> {% endif %}
</div>
<div style="padding-top: 67px" class = "disciplinas-container">
    {% for disciplina in disciplinas_list %}
        <div class = "disciplina">
            <a href="{% url 'sitemestrado:detalhedisc' disciplina.id %}"> 
                <h3 style="display:inline-block"> {{ disciplina.disciplina_sigla }}</h3> -
                <h4 style="display:inline-block"> {{ disciplina.disciplina_nome }} </h4> 
            </a>
        </div>
    {%endfor%}
</div>
{% endblock %}

{% block footer %}
{% endblock %}

sitemestrado/templates/sitemestrado/forum.html
{% extends "sitemestrado/index.html" %}
{% load static %}

{% block title %}
  <title> Fórum </title>
{% endblock %}

{%block searchbar%}
<form class='search-form' method=POST action ="{% url 'sitemestrado:searchpost' %}">
  {% csrf_token %}
 <input type='search' placeholder='Search' name ="searched">
 <button class'search-btn' type='submit'>Search</button>
</form>  
{%endblock%}

{% block eventos-list %}
{% endblock %}

{% block content %}
<div class="noticias-title-and-button">
<h2 style="display: inline-block; padding-left:0.5%;"> Fórum </h2> <button class="buttons-default" onclick="window.open('criarpost','_self')"> Criar post</button>
</div>
<div style="padding-top: 67px">
    {% if post_list %}
      {% for post in post_list %}
          <div class="post-layout">
            <div class="post-capa">
            <a href="{% url 'sitemestrado:detalhepost' post.id %}">
            {% if post.post_capa %}
             <img src=" {{ post.post_capa }}">
            {% else %}
             <img src="{% static "/imagens/defaultnoticia.png" %}">
            {% endif %}
            </a>
            </div>
            <div class="post-container">
              <div class="post-nome-e-autor">
                <a href="{% url 'sitemestrado:detalhepost' post.id %}">
                <h1 style="margin: 0"> {{ post.post_nome }} </h1>
                </a>
                <h3 style="margin-top:0"> Publicado por <a href="{% url 'sitemestrado:infooutrapessoa' post.post_autor_id %}">{{ post.post_autor }} </a> </h3>
              </div>
              <div class="post-data">
                Data de publicação: {{ post.post_data_pub }}
              </div>
              <div class="post-conteudo">
                Texto: {{ post.post_conteudo }}
              </div>
              <div class="post-nr-respostas">
                Número de respostas: {{ post.post_nr_respostas }}
              </div>
            </div>
          </div>
      {% endfor %}
    {% else %}
      <h1> Ainda não houve posts publicados </h1>
    {% endif %}
      </div>
{% endblock %}

{% block footer %}
{% endblock %}

sitemestrado/templates/sitemestrado/index.html
<!DOCTYPE>
<html>
    <head>
        {% load static %}
         <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}"> 
         <link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}"> 
         <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}"> 
         <link rel="shortcut icon" href="{% static '/imagens/favicon.ico' %}" type="image/x-icon">
        {%block title%}
        <title> Comunidade de Alunos/Ex-alunos e Professores do Mestrado de Business Analytics </title>
        {% endblock%}
    </head>
    <body>
      <div class="login-container" style="position: fixed; top:0; right:0; z-index:5; background-color:rgb(197, 182, 159)" >
          {% if request.user.is_authenticated %}
                    <div style="display: inline-block"> 
                      {{ request.user.first_name }} {{ request.user.last_name }}
                    </div>
                    <div class="logo-container" style="display: inline-block"> 
                      {% if request.user.aluno.imagem %}
                        <img src="{{ request.user.aluno.imagem }}" height="25px">
                      {% else %}
                        <img src="{% static '/imagens/defaultprofilepic.png' %}" height="25px">
                      {% endif %}
                      <button class="buttons-default" onclick="window.open('logoutpage','_self')">Logout </button> 
                    </div>
                 {% else %}
                    <button class="buttons-default" onclick="window.open('loginpage','_self')"> Login</button>
                    <button class="buttons-default" onclick="window.open('registar','_self')"> Registar </button>
                {% endif %}
      </div>
      <div class="scroll-white-top">
      </div>
      <header class="menu">
        <nav id='menu'>
          <ul>
            <li><a href="{% url 'sitemestrado:index' %}">Página Inicial</a></li>
            <li><a href="{% url 'sitemestrado:forum' %}">Fórum</a></li>
            <li><a href="{% url 'sitemestrado:eventos' %}">Eventos</a></li>
            <li><a href="{% url 'sitemestrado:disciplinas' %}">Disciplinas</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'sitemestrado:infopessoal' %}">Informações Pessoais</a></li>
            {% endif %}
          </ul>
        </nav>
        {% block eventos-list %}
        <div class="eventos-absolute-container">
          <div class="eventos-list-three">
            {% if three_eventos %}
             {% for evento in three_eventos %}
             <a href="{% url 'sitemestrado:detalheevento' evento.id %}">
             <div class="evento-layout">
               <div class="evento-capa">
                {% if evento.evento_capa %}
                  <img src=" {{ evento.evento_capa }}">
                {% else %}
                  <img src="{% static '/imagens/defaultnoticia.png' %}">
                {% endif %}
               </div>
               <div class="evento-nome-and-data-container">
                  <h5 style="margin:0"> {{ evento.evento_data }} </h5>
                  <h3> {{ evento.evento_nome }} </h3>
                  <h4 style="margin:0"> {{ evento.evento_local }} </h4>
               </div>
              </div>
            </a>
             {% endfor %}
            {% endif %}
          </div>
        </div>
        {% endblock %}
        <div class="searchbar-container">
          {%block searchbar%}
          <form class='search-form' method=POST action ="{% url 'sitemestrado:searchuser' %}">
            {% csrf_token %}
            <input style="height:25px" type='search' placeholder='Search' name ="searched">
          <button class'search-btn' type='submit'>Search</button>
          </form>   
          {%endblock%}
        </div>
      </header>
      <div class="body-container">
        {% block content %}
        <div class="content-container">
          <div class="noticias-container-left">
            <div class="noticias-title-and-button">
              <div class="noticias-title">
                <h2 style="padding-left:5%;"> Notícias <h2> 
              </div>    
              <div class="noticias-add-button">
                <button class="buttons-default" onclick="window.open('criarnoticia','_self')"> Criar notícia </button>
              </div>
              <div class="eventos-title">
                <a href="{% url 'sitemestrado:eventos' %}"> <h2 style="display: inline-block;"> Eventos </h2></a>
              </div> 
            </div>
            <div class="noticias-list"> 
              {% if noticias_list %}
                {% for noticia in noticias_list %}
                  <div class="noticia-layout">
                    <div class="noticia-imagem">
                      <a href="{% url 'sitemestrado:detalhenoticia' noticia.id %}">
                        {% if noticia.noticia_capa %}
                            <img src=" {{ noticia.noticia_capa }}">
                        {% else %}
                            <img src="{% static "/imagens/defaultnoticia.png" %}">
                        {% endif %}
                      </a>
                    </div>
                    <div class="noticias-autor-data">
                      <div class="noticia-autor" >
                        <a href="{% url 'sitemestrado:infooutrapessoa' noticia.noticia_autor_id %}"> {{noticia.noticia_autor}}</a>
                      </div>
                      <div class="noticia-data">
                        {{ noticia.noticia_data_pub }}
                      </div>
                    </div>
                    <div class="noticia-nome">
                      <a href="{% url 'sitemestrado:detalhenoticia' noticia.id %}">
                        {{ noticia.noticia_nome }}
                      </a>
                    </div>
                  </div>
                  {% endfor %}
              {% else %}
                <p> Não há notícias de momento. </p>
              {% endif %}
            </div>
         </div>
          <div class="eventos-container-right">
          </div>
       </div>
       {% endblock %}
      </div>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
      <script src="{% static 'js/script.js' %}"></script>
    </body>
    {% block footer %}
    <div class="footercontainer" id="footercontainer">
      <div class="footer">
          <div class = "esq">
              <div class = "morada">
                  <h4>Iscte - Instituto Universitário de Lisboa</h4>
                  <h4>Avenida das Forças Armadas, 1649-026 Lisboa</h4>
              </div>
  
          </div>
          <div class = "meio">
                  <h4>Comunidade de Alunos/Ex-alunos e Professores do Mestrado de Business Analytics</h4>
                  <h4> Coordenador do Mestrado: Raul Laureano </h4>
          </div>
          <div class = "dir">
              <div class=" Contactos">
                  <h4>Contactos: </h4>
                  <a href="mailto:dbpgo@iscte-iul.pt">Diogo Peng</a> </br>
                  <a href="mailto:dslor@iscte-iul.pt">Duarte Laureano</a></br>
                  <a href="mailto:jarcv@iscte-iul.pt">João Pereira</a></br>
              </div>
          </div>
      </div>
    </div>
    {% endblock %}
</html>

sitemestrado/templates/sitemestrado/searchuser.html
{% extends "sitemestrado/index.html" %}

{% block title %}
  <title> Resultado da pesquisa  </title>
{% endblock %}

{% load static %}

{%block searchbar%}
<form class='search-form' method=POST action ="{% url 'sitemestrado:searchuser' %}">
  {% csrf_token %}
 <input type='search' placeholder='Search' name ="searched">
 <button class'search-btn' type='submit'>Search</button>
</form>  
{%endblock%}

{% block eventos-list %}
{% endblock %}

{% block content %}
{%if searched %}
<h1> Resultados da pesquisa: </h1>
    {% for user in listausers %}
    <a href="{% url  'sitemestrado:infooutrapessoa' user.id %}">
        <div style="display:inline-block">
          {% if user.aluno.imagem %}
            <img src="{{ user.aluno.imagem }}" height="100px">
          {% else %}
            <img src="{% static '/imagens/defaultprofilepic.png' %}" height="100px">
          {% endif %}
        </div>
        <div style="display:inline-block">
          <h1> {{user.first_name }} {{user.last_name }} </h1>
        </div>
    </a>
    <br>
    {%endfor%}
{%else%}
    <h1>No Search</h1>
{%endif%}
{% endblock %}

{% block footer %}
{% endblock %}